### ISSUE TITLE
Add button for pathname generation

### ISSUE THREAD

**Issue by markomitranic** [tinloof/sanity-kit#19]
Heh, a customer asked me "where did the generate button go" today :D 

I can easily add a generate button, similar to what the original slug field has.

I can't do that this week tho, so opening this issue to keep track of this :)

**Comment by siffogh** [comment]
@markomitranic curious to see you approach as I don't see where to fit it in conjunction with the "Preview" button.

**Comment by markomitranic** [comment]
@siffogh not sure :P I was thinking perhaps a little refresh icon within the input field on the right side.

**Comment by Jamiewarb** [comment]
I had a solution to propose.

The "Preview" button is used to change the document being previewed in Presentation mode. However it also appears in documents in Structure, albeit disabled. It's also not related to the slug field, but to the presentation preview (despite it using the slug field to decide what to preview).

So I wanted to float the idea so changing "Preview" back to "Generate", then adding the "Preview" setting back in a slightly different way:

When editing a slug field, when the user leaves focus and the folders "lock", we could also automatically update the Presentation preview URL if it matches the old slug.

My thinking behind this is, as "Generate" is an action on the slug field, it makes sense to be on the slug field UI, whereas "Preview" is an action on the Presentation UI so makes less sense to have a button for that action on the slug field

If the above isn't ideal, then we could look to move that action somewhere else, following the above thought process, such as a button that only appears in Presentation mode, beneath the document title, for instance

**Comment by marcusforsberg** [comment]
#65 in conjunction with #63 should hopefully solve this quite nicely, along the lines of @Jamiewarb's suggested approach. 😊
