### ISSUE TITLE
`canUnlock` does not work on initial load of new Page

### ISSUE THREAD

**Issue by tamaccount** [tinloof/sanity-kit#36]
Hi. I'm using the new `folder.canUnlock` property, and it's now working properly.

Here's how my schema looks:
```
definePathname({
    name: "pathname",
    initialValue: {
      current: '/authors/',
    },
    options: {
      folder: {
        canUnlock: false,
      },
      i18n: {
        enabled: true,
        defaultLocaleId: config.i18n.defaultLocaleId,
      },
    },
  }),
``` 

Despite having `canUnlock: false`, the full pathname is still editable when I create a new Page.
![Frame 427319344](https://github.com/tinloof/sanity-kit/assets/15708264/4b7bbb3f-e107-4f98-8184-f2367238b893)

Here's a video, with more detail:

https://github.com/tinloof/sanity-kit/assets/15708264/ac5cfc08-b496-44da-ba4a-a2b377b67fa9

Please make it so `canUnlock: false` works properly on initial load.

**Comment by thomasKn** [comment]
@tamaccount can you confirm the issue is fixed with the `v1.1.3` release?
